services:
  - type: web
    name: campus-platform
    runtime: python
    plan: free
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: MONGO_URI
        sync: false
      - key: DB_NAME
        value: campus_platform
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: ADMIN_SIGNUP_CODE
        sync: false
      - key: JWT_ACCESS_TOKEN_EXPIRES_DAYS
        value: 7
